### ISSUE TITLE
Bug kontrol snek

### ISSUE THREAD

**Issue by arshana40** [Dimas0075/Snake#2]
Misal snake sedang bergerak, tekan dengan cepat tombol yang arahnya tidak berlawanan/searah dengan arah gerak snake, lalu segera tekan tombol berlawanan arah dengan arah snake semula. Snake akan bergerak menembus tubuhnya sendiri, dan kalau snake sudah memiliki panjang tertentu, dapat langsung berakibat game over.

Contoh:
Snake bergerak ke kanan,
dengan cepat tekan bawah, lalu kiri.
snake bisa jadi menembus tubuhnya sendiri ::
bukan begini: 
----->1  ...............................................1 .... 3 ...  2
...3.....| 2............... tapi jadinya......... ----<===
....<= v

Nanti aku coba benerin, tapi aku tulis di sini siapatahu ada yg tahu cara membenarkannya.

**Comment by Dimas0075** [comment]
Setelah gameover, ada yang tau cara ngubah biar kecepatan snakenya kembali ke awal?

**Comment by arshana40** [comment]
coba cek yg pull requestku.
seharusnya kalau aku tinggal DELAY = 100; (nilai awal)
timer.setDelay(DELAY);
